services:
  whisper-gpu:
    build:
      context: .
      dockerfile: docker/dockerfile.whisper.gpu
    container_name: whisper-gpu-test
    environment:
      - NVIDIA_VISIBLE_DEVICES=all 
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility  
    stdin_open: true 
    tty: true  
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./volumes/whisper:/whisper/data  
    working_dir: /whisper
    runtime: nvidia  
