services:
  whisper:
    build:
      context: ./docker/whisper  
      dockerfile: dockerfile.whisper.cpu
    container_name: whisper_api_cpu_container
    environment:
      - PULSE_SERVER=unix:/run/user/${UID}/pulse/native
      - PULSE_COOKIE=/run/user/${UID}/pulse/cookie
    volumes:
      - /dev/snd:/dev/snd  
      - /run/user/${UID}/pulse:/run/user/${UID}/pulse  
      - ~/.config/pulse/cookie:/run/user/${UID}/pulse/cookie:ro  
    devices:
      - /dev/snd 
    ports:
      - "8080:8080"  
    restart: unless-stopped 

volumes:
  audio_data:
    driver: local
