ARG IMAGE=ubuntu:22.04
FROM ${IMAGE}

ENV DEBIAN_FRONTEND=noninteractive
ENV WORKDIR=/whisper

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    build-essential \
    cmake \
    libsdl2-dev \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/ggerganov/whisper.cpp.git $WORKDIR

WORKDIR $WORKDIR

RUN cmake -B build -DWHISPER_SDL2=ON && \
    cmake --build build -j$(nproc) --config Release && make -j medium

CMD ["bash"]
